# Generated by Django 4.0.5 on 2023-06-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reserva_nombrehijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut de cuidador')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de cuidador')),
                ('edad', models.IntegerField(max_length=10, verbose_name='Edad de cuidador')),
                ('email', models.CharField(max_length=40, verbose_name='Email de cuidador')),
                ('numero', models.IntegerField(max_length=10, verbose_name='Numero de telefono')),
                ('dire', models.CharField(max_length=100, verbose_name='Dirección')),
                ('experiencia', models.CharField(max_length=500, verbose_name='Experiencia')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen de cuidador')),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
    ]
