# Generated by Django 4.0.5 on 2023-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cuidador_remove_reserva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.CharField(default=0.0002827454584010744, max_length=20),
            preserve_default=False,
        ),
    ]
