# Generated by Django 4.0.5 on 2023-06-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
