# Generated by Django 4.2.2 on 2023-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reserva_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombrehijo', models.CharField(max_length=50, verbose_name='Nombre Hijo')),
                ('ruthijo', models.CharField(max_length=12, verbose_name='Rut Hijo')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('horas_reserva', models.IntegerField(verbose_name='Cantidad de Horas')),
            ],
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
