# Generated by Django 4.0.5 on 2023-06-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tiposoporte_soporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposoporte',
            name='id_tipo_s',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
