# Generated by Django 4.2.1 on 2023-06-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_soporte_tipo_s_delete_tiposoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='calificacion',
            field=models.CharField(default='Sin calificaciones recientes', max_length=500, verbose_name='Calificación reciente'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='edad',
            field=models.IntegerField(verbose_name='Edad de cuidador'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='numero',
            field=models.IntegerField(verbose_name='Numero de telefono'),
        ),
    ]
